name: wenia
description: "Wenia crypto app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  firebase_core: '3.1.1'
  firebase_auth: '5.1.1'
    
  # Style
  cupertino_icons: ^1.0.6
  google_fonts: '6.2.1'

  # State
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.3

  #Services
  http: ^1.2.1

  # required
  path_provider_foundation: ^2.4.0

  #Database
  sqflite: '2.3.0'
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/core/assets/img/wenia-logo.png
    - lib/core/assets/img/bye.png